server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: ms-email
  profiles.active: dsv
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        proc.param_null_passing: true
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.Oracle12cDialect
  mail:
    host: smtp.****.com
    port: 999
    username: MyemailUser@*****.com
    password: MySmtpUserPassword
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
    isEnableSsl: true
    isEnableAuth: true

---
spring:
  profiles: dsv # profile for test enviroment locally in Windows
  datasource:
    url: jdbc:oracle:thin:@DB202201311355_high?TNS_ADMIN=C:/pathtoWalllet/Wallet_***** # path wallet for autonomous database configuration
    username: myOraUserName
    password: myOraPassword
---
spring:
  profiles: homolog # profile for homologation enviroment phase in Linux
  datasource:
    url: jdbc:oracle:thin:@DB202201311355_high?TNS_ADMIN=/****/wallet_*****
    username: myOraUserName
    password: myOraPassword
---
