server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: ms-email
  profiles.active: dsv
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        proc.param_null_passing: true
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.Oracle12cDialect
  mail:
    host: ${SMTP_HOST:root}
    port: ${SMTP_PORT:root}
    username: ${SMTP_USER:root}
    password: ${SMTP_PWD:root}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
    isEnableSsl: true
    isEnableAuth: true

---
spring:
  profiles: dsv # profile for test enviroment locally in Windows
  datasource:
    url: jdbc:oracle:thin:@${ORA_DBNAME:root}_high?TNS_ADMIN=C:/projects/Wallet_${ORA_DBNAME:root} # path wallet for autonomous database wallet
    username: ${ORA_USER:root}
    password: ${ORA_PWD:root}
---
spring:
  profiles: homolog # profile for homologation enviroment phase in Linux
  datasource:
    url: jdbc:oracle:thin:@DB*****_high?TNS_ADMIN=/****/wallet_*****
    username: myOraUserName
    password: myOraPassword
---
